# /// script
# requires-python = ">=3.11,<3.12"
# ///
"""catalog_page.py — render THE LIST (D-008 catalog campaign, deliverable face 2). Reads catalog.jsonl
and generates reports/catalog/index.html (filterable/sortable, grouped, badges, live URLs) + CATALOG.md
(fallback). Headline = TOTAL ENTRIES split by status. Regenerated on every ingest; served by serve.sh.
Self-contained HTML (inline CSS/JS), theme-aware, no external requests.
"""
import json, pathlib, html
from collections import Counter
ROOT = pathlib.Path(__file__).resolve().parents[2]

BADGE = {"auto_acquired_verified": ("✓ verified", "#1a7f37"),
         "click_to_get": ("↓ click-to-get", "#9a6700"),
         "excluded": ("✕ excluded", "#82071e")}


def main():
    rows = [json.loads(l) for l in open(ROOT / "catalog.jsonl") if l.strip()]
    total = len(rows)
    by_status = Counter(r["status"] for r in rows)
    by_market = Counter(r.get("marketplace") or "?" for r in rows)
    verified = by_status.get("auto_acquired_verified", 0)
    working = sum(1 for r in rows if r.get("gate_state") in ("pass", "partial"))

    # ---- CATALOG.md ----
    md = [f"# THE CATALOG — free procedural Blender tooling\n",
          f"**TOTAL CATALOG ENTRIES: {total}**  ·  ✓ verified {by_status.get('auto_acquired_verified',0)} · "
          f"↓ click-to-get {by_status.get('click_to_get',0)} · ✕ excluded {by_status.get('excluded',0)}  ·  "
          f"({working} gated working)\n",
          "By marketplace: " + " · ".join(f"{m} {n}" for m, n in by_market.most_common()) + "\n",
          "\n_Regenerated by catalog_page.py on every ingest. Full filterable page: reports/catalog/index.html_\n"]
    (ROOT / "CATALOG.md").write_text("\n".join(md))

    # ---- index.html ----
    def esc(x):
        return html.escape(str(x)) if x is not None else ""
    trs = []
    for r in rows:
        label, color = BADGE.get(r["status"], (r["status"], "#666"))
        url = r.get("url") or ""
        name = esc(r.get("name") or r["catalog_id"])
        link = f'<a href="{esc(url)}" target="_blank" rel="noopener">{name}</a>' if url else name
        trs.append(
            f'<tr data-status="{esc(r["status"])}" data-market="{esc(r.get("marketplace"))}" '
            f'data-cat="{esc(r.get("category") or "")}" data-prov="{1 if r.get("provisional") else 0}">'
            f'<td>{link}</td><td>{esc(r.get("creator") or "")}</td>'
            f'<td>{esc(r.get("marketplace"))}</td>'
            f'<td><span class="badge" style="background:{color}">{esc(label)}</span>'
            f'{" <span class=prov>prov</span>" if r.get("provisional") else ""}</td>'
            f'<td>{esc(r.get("gate_state") or "")}</td>'
            f'<td>{esc(r.get("price_class") or "")}</td>'
            f'<td>{esc(r.get("license") or "")}</td>'
            f'<td>{esc(r.get("category") or "")}</td></tr>')
    markets = "".join(f'<option value="{esc(m)}">{esc(m)} ({n})</option>' for m, n in by_market.most_common())
    page = f"""<!doctype html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1">
<title>Blender Vault Catalog — {total} entries</title><style>
:root{{color-scheme:light dark}} body{{font:14px/1.5 system-ui,sans-serif;margin:0;padding:1rem;max-width:100%}}
h1{{font-size:1.4rem;margin:.2rem 0}} .head{{position:sticky;top:0;background:Canvas;padding:.5rem 0;z-index:2;border-bottom:1px solid #8884}}
.stat{{display:inline-block;margin-right:1rem;font-weight:600}} .big{{font-size:1.6rem;color:#1a7f37}}
input,select{{font:inherit;padding:.3rem;margin:.2rem}} table{{border-collapse:collapse;width:100%;font-size:13px}}
th,td{{text-align:left;padding:.35rem .5rem;border-bottom:1px solid #8883;vertical-align:top}}
th{{cursor:pointer;position:sticky;top:4.2rem;background:Canvas}} .badge{{color:#fff;padding:.1rem .4rem;border-radius:.3rem;font-size:11px;white-space:nowrap}}
.prov{{font-size:10px;color:#9a6700;border:1px solid #9a6700;border-radius:.2rem;padding:0 .2rem}}
a{{color:#0969da}} @media(prefers-color-scheme:dark){{a{{color:#58a6ff}}}} #wrap{{overflow-x:auto}}
</style></head><body>
<div class=head><h1>🗂️ Blender Vault Catalog</h1>
<div><span class="stat big">{total} entries</span>
<span class=stat style="color:#1a7f37">✓ {by_status.get('auto_acquired_verified',0)} verified</span>
<span class=stat style="color:#9a6700">↓ {by_status.get('click_to_get',0)} click-to-get</span>
<span class=stat style="color:#82071e">✕ {by_status.get('excluded',0)} excluded</span>
<span class=stat>({working} gated working)</span></div>
<div><input id=q placeholder="filter name/creator/category…" oninput=f()>
<select id=st onchange=f()><option value="">all status</option><option>auto_acquired_verified</option><option>click_to_get</option><option>excluded</option></select>
<select id=mk onchange=f()><option value="">all marketplaces</option>{markets}</select>
<label><input type=checkbox id=hideprov onchange=f()> hide provisional</label></div></div>
<div id=wrap><table id=t><thead><tr>
<th onclick=s(0)>Name</th><th onclick=s(1)>Creator</th><th onclick=s(2)>Marketplace</th>
<th onclick=s(3)>Status</th><th onclick=s(4)>Gate</th><th onclick=s(5)>Price</th><th onclick=s(6)>License</th><th onclick=s(7)>Category</th>
</tr></thead><tbody>{''.join(trs)}</tbody></table></div>
<script>
const T=document.getElementById('t'),rows=[...T.tBodies[0].rows];
function f(){{const q=document.getElementById('q').value.toLowerCase(),st=document.getElementById('st').value,
mk=document.getElementById('mk').value,hp=document.getElementById('hideprov').checked;
for(const r of rows){{const t=r.textContent.toLowerCase();
r.style.display=(!q||t.includes(q))&&(!st||r.dataset.status==st)&&(!mk||r.dataset.market==mk)&&(!hp||r.dataset.prov=='0')?'':'none';}}}}
let sd=1;function s(i){{sd=-sd;rows.sort((a,b)=>sd*(a.cells[i].textContent||'').localeCompare(b.cells[i].textContent||''));
const tb=T.tBodies[0];rows.forEach(r=>tb.appendChild(r));}}
</script></body></html>"""
    outdir = ROOT / "reports/catalog"; outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "index.html").write_text(page)
    print(json.dumps({"total_entries": total, "html": str(outdir / "index.html"),
                      "md": str(ROOT / "CATALOG.md"), "by_status": dict(by_status)}))


if __name__ == "__main__":
    main()
